# Generated by Django 4.0.1 on 2022-02-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_bid_user_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidders',
        ),
    ]
