# Generated by Django 4.0.1 on 2022-02-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
