# Generated by Django 4.0.1 on 2022-02-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='auctions')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionphotos'),
        ),
    ]
