# Generated by Django 4.0.1 on 2022-02-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionphotos_alter_auction_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='auctionphotos',
            name='photo',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='auctionphotos',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionphotos',
            name='images',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
