# Generated by Django 4.0.1 on 2022-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_photo_remove_auctionphotos_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_description',
            field=models.CharField(max_length=900),
        ),
    ]
