# Generated by Django 4.0.1 on 2022-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
