# Generated by Django 4.0.1 on 2022-03-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_item_title_alter_auction_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
    ]
