# Generated by Django 4.0.1 on 2022-03-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionphotos',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auction'),
        ),
    ]
