# Generated by Django 4.0.1 on 2022-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_image_url_delete_auctionphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='listing_duration',
            field=models.IntegerField(default=48),
            preserve_default=False,
        ),
    ]
