# Generated by Django 4.0.1 on 2022-03-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bid_auction_alter_bid_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['amount']},
        ),
    ]
