# Generated by Django 4.0.1 on 2022-03-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['posted_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postedDate',
            new_name='posted_date',
        ),
    ]
