# Generated by Django 4.0.1 on 2022-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='listing_duration',
            field=models.TimeField(),
        ),
    ]
