# Generated by Django 4.0.1 on 2022-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auction_listing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='listing_duration',
            field=models.DateTimeField(),
        ),
    ]
