# Generated by Django 4.0.1 on 2022-03-13 13:33

import auctions.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_auction_listing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='listing_duration',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Cannot be in the past.', validators=[auctions.models.validate_listing_duration]),
        ),
    ]
