# Generated by Django 4.0.1 on 2022-03-13 14:13

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_auction_listing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='listing_duration',
            field=models.DateTimeField(help_text='Cannot be in the past.', validators=[auctions.models.validate_listing_duration]),
        ),
    ]
