# Generated by Django 4.0.1 on 2022-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_auction_listing_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bid',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
