# Generated by Django 4.0.1 on 2022-03-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auction_highest_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
    ]
