# Generated by Django 4.0.1 on 2022-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_alter_bid_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highest_bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
    ]
