# Generated by Django 4.0.1 on 2022-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_remove_auction_highest_bid_alter_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_finished',
            field=models.BooleanField(default=False),
        ),
    ]
