# Generated by Django 4.0.1 on 2022-09-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_user_auctions_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='listing_duration',
            new_name='expiry_date',
        ),
    ]
